spring:
  datasource:
    password: 123
    username: root
    url: jdbc:mysql://localhost:3306/1911_wechat
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  type-aliases-package: com.qf.entity